[tool.poetry]
name = "acl4ssr-azure"
version = "0.1.0"
description = "Just for personal usages"
authors = ["CLiKader <git@clikader.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
